name: Deploy

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  build-wheels:
    name: build-wheels
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      run: pip install numpy pybind11 wheel
    - name: Clone tensorflow 
      uses: actions/checkout@master
      with:
        repository: tensorflow/tensorflow
    - name: Build wheel
      run: PYTHON=python{{ $matrix.python-version }} tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh native
      with:
        python-version: ${{ matrix.python-version }}
      shell: bash
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: wheel-${{ matrix.platform }}-${{ matrix.python-version }}
        path: tensorflow/lite/tools/pip_package/gen/tflite_pip/python3/dist/*.whl

  upload-wheels:
    needs: build-wheels
    name: upload-wheels
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
    - name: Prepare upload
      run: |
        mkdir upload
        find . -name '*.whl' | xargs cp -t upload/
        ls -lR
